name: Build

on:
  push:
    paths-ignore:
      - '*.md'
      - 'assets/*'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  BUILD_PROFILE: release

jobs:
  build:
    name: Build Quilt
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macos-latest", "windows-latest", "ubuntu-latest" ]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --profile ${{ env.BUILD_PROFILE }} --verbose
      # - name: Run tests
      #   run: cargo test --verbose
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Quilt-${{ matrix.os }}
          path: target/release/quilt*
          if-no-files-found: error